# Generated by Django 5.0 on 2024-01-12 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovelAPI', '0002_novel_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='content',
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NovelAPI.novel')),
            ],
        ),
    ]
