# Generated by Django 5.0 on 2024-01-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovelAPI', '0003_remove_novel_content_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='pub_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
