# Generated by Django 5.0.1 on 2024-01-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovelAPI', '0004_chapter_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='novel',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='novel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
