# Generated by Django 5.0.1 on 2024-01-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NovelAPI', '0005_chapter_read_count_novel_dislikes_novel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
